import {
  BEST_SELLERS_SECTION_VALUE,
  COMING_SOON_SECTION_VALUE,
  NEW_ARRIVALS_SECTION_VALUE,
  POPULAR_SECTION_VALUE,
  SPECIAL_OFFERS_SECTION_VALUE,
  sectionNames,
} from './values';

export {
  BEST_SELLERS_SECTION_VALUE,
  COMING_SOON_SECTION_VALUE,
  NEW_ARRIVALS_SECTION_VALUE,
  POPULAR_SECTION_VALUE,
  SPECIAL_OFFERS_SECTION_VALUE,
  sectionNames,
};
